name: main
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - uses: pre-commit/action@v3.0.0

  tests:
    strategy:
      matrix:
        python_version: ["3.9", "3.10", "3.11"]
        type: ["small", "large"]
        exclude:
          - python_version: "3.11"
            type: "large"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}
      - name: Install jobsim
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
          pip install pytest

      - name: run ${{ matrix.type }}-tests
        run: python -m pytest -v --junitxml=${{ matrix.type }}_tests_results.xml tests/${{ matrix.type }}
#        run: poetry run pytest -s -v tests/small


  report_workflow:
    if: always()
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: uoboda-splunk/workflow-info-splunk-upload-action@v1
        with:
          splunk_host: ${{ secrets.SPLUNK_HOST }}
          splunk_token: ${{ secrets.SPLUNK_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
